### PR TITLE
Render route marker + miscellaneous fixes

### PR DESCRIPTION
**Pull request by tony56a**
These changes implement a minimal version of #7 ( basically just a texture mesh, and a textmesh on top, and the texture and textmesh positioning are hardcoded atm), along with:
1. Fixing the used name/route panels so that they properly count the number of references in the map
2. The ability to close all panels when clicking on the close button on any panel/ the UI toolbar close button
3. A proposed fix for some of the CTD cases when loading a map(just add a meshrenderer to prevent null pointer issues on all mesh gameobjects)

The next version should implement the use of other route shield textures(maybe a config file or something?), attempting to merge the route meshes together, and a general cleanup of the code.

### CODE REVIEW

**Comment by PropaneDragon** [comment]
Great stuff. I've not forgotten about any of this, so your work isn't going to waste! I just haven't had the chance to merge everything yet.

**Comment by PropaneDragon** [comment]
I've tried merging this in and get an error when initially loading up in C:S. Does this happen to you too?

**Comment by tony56a** [comment]
If it's a CTD, I suspect it may be an issue with meshRenderer being null with some of the roadName/Route objects. I'll take a look at it ASAP.

**Comment by PropaneDragon** [comment]
It's not a CTD, but the mod fails to load up. I'm guessing something's failing to deserialise somewhere, but it only appears when I merge your changes.

**Comment by tony56a** [comment]
Was the exception logged? Looking at it now, I think it might just be me forgetting to add a line to the post-build script to copy the route shield textures to the correct directory.

**Comment by PropaneDragon** [comment]
It was logged, but rather intelligently I didn't copy the error. I'll copy
it tomorrow, but it was definitely while it was trying to deserialise
something.

**Comment by tony56a** [comment]
Superceded by #12

**Pull request closed without merging**
